QE-118 qi 02 add questions using the top bar
LimeSurvey/react-app pull request #40
Opened 2023-05-19 16:46 UTC by ramishenouda48

1. Updated the add question in the top bar to add questions to the last or focused question group.
2. Focusing on the title of the newly added question.
3. Updated misleading variable names.

![topbar](https://github.com/LimeSurvey/react-app/assets/129734454/34f12b20-d29c-422a-bb9c-9010dc5a444d)

2023-05-23 11:56 UTC, d-Pixie requested changes

2023-05-23 11:56 UTC, d-Pixie commented on src/components/Survey/AddQuestion/AddQuestion.js
> +        toggleEventListener(show)
`toggleEventListener` sounds wrong here. I'm guessing from context that this is `onToggle`?

2023-05-23 11:56 UTC, d-Pixie commented on src/components/SurveyStructure/RowQuestionGroup.js
> +    updateFocusedQuestion(question)
A name like `setFocusedQuestion` or `focusQuestion` is better. The current name implies that the focused question is updated, not that you are updating which question is focused.

2023-05-23 11:56 UTC, d-Pixie commented on src/helpers/ScrollToQuestion.js
> +  const questionElement = document.getElementById(`${question.qid}-question`)
No, you are not allowed to do this 😄 Read up on [refs and the DOM](https://legacy.reactjs.org/docs/refs-and-the-dom.html) and switch to using a ref here.

2023-05-23 11:56 UTC, d-Pixie commented on src/pages/Editor/TopBar/TopBar.js
> +  const handleOnAddQuestionToggle = () => {
I'm not sure what this should be called, but maybe this is `onAddQuestion`?

2023-05-23 11:56 UTC, d-Pixie commented on src/pages/Editor/TopBar/TopBar.js
> +      questionGroup = survey.questionGroups.filter(
Firstly `filter` returns more than one element, which you know since you are returning the `[0]` element of the result. Using [`find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) instead you always get the first result and exit early if it is found. It also returns `undefined` if it can't find anything so you can do:
```js
let questionGroup = survey.questionGroups.find((questionGroup) =>
          questionGroup.gid === focusedQuestionQuestionOrGroup?.gid || questionGroup.gid === 
 focusedQuestionGroup?.gid ) || survey?.questionGroups[survey?.questionGroups?.length - 1]
```
But if you change to using index to keep track of the selected group instead you can just do:
```
let index = focusedQuestionGroupIndex || focusedQuestionQuestionOrGroupIndex || survey.questionGroups.length - 1
let questionGroup = survey.questionGroups[ index ]
```
This requires you to set the `...Index` states to `undefined` when nothing is selected and either except if someone tries to load a survey that doesn't exist ( in the `const { survey, update } = useSurvey(surveyId)` call), adding a [ErrorBoundary](https://legacy.reactjs.org/docs/error-boundaries.html), or making sure that you have a null object return from `useSurvey` at all times.

In this case the null object would have a `questionGroups` attribute that is an array. So this would be enough for this use case: `{ questionGroups: [] }`, but you will have to extend that over time to allow you to reason about your code confidently and not have defensive programming everywhere (things like `if` `?.` etc are defensive).

2023-05-24 02:17 UTC, ramishenouda48 commented on src/components/Survey/AddQuestion/AddQuestion.js
> +        toggleEventListener(show)
make sense, renamed to `onToggle`

2023-05-24 02:21 UTC, ramishenouda48 commented on src/components/SurveyStructure/RowQuestionGroup.js
> +    updateFocusedQuestion(question)
renamed to `setFocusedQuestion`

2023-05-24 02:24 UTC, ramishenouda48 commented on src/helpers/ScrollToQuestion.js
> +  const questionElement = document.getElementById(`${question.qid}-question`)
nice one, makes a lot of sense. I will update that in another PR

2023-05-24 02:26 UTC, ramishenouda48 commented on src/pages/Editor/RightSideBar/RightSideBar.stories.js
> +  const [, updateFocusedQuestion] = useFocusedQuestionOrGroup()
looks neat, I will update it in another PR.

2023-05-24 02:29 UTC, ramishenouda48 commented on src/pages/Editor/TopBar/TopBar.js
> +  const handleOnAddQuestionToggle = () => {
it should happen when the user toggles the `addQuestion` overlay, even if they didn't add a question.
![image](https://github.com/LimeSurvey/react-app/assets/129734454/21e352e6-ec5d-49fb-b12c-ab2fa127be70)
![image](https://github.com/LimeSurvey/react-app/assets/129734454/9c6a3cc7-25cf-495d-a05f-2c7bc872fd29)

I have renamed it to `onAddQuestionToggle`

2023-05-24 02:43 UTC, ramishenouda48 commented on src/pages/Editor/TopBar/TopBar.js
> +      questionGroup = survey.questionGroups.filter(
thank you! very informative. I have updated it to =>
```javascript
  const onAddQuestionToggle = () => {
    const questionGroup =
      survey.questionGroups.find(
        (questionGroup) => questionGroup.gid === focusedQuestionOrGroup?.gid
      ) || survey?.questionGroups[survey?.questionGroups?.length - 1]

    setFocusedQuestionGroup(questionGroup)
  }
```

2023-05-24 02:54 UTC, ramishenouda48 commented on src/pages/Editor/TopBar/TopBar.js
> +    const updatedQuestionGroups = survey.questionGroups.map((questionGroup) => {
I'm not sure about this one, might complicate other functions🤔?

2023-05-24 09:01 UTC, merged