QE-21 sb 04 question
LimeSurvey/react-app pull request #41
Opened 2023-05-23 03:26 UTC by ramishenouda48

1. Updated the question drag and drop functionality to be dragged from the question title instead of an icon
2. Add Question meatball menu
3. Added Question duplication
4. Added question deletion

![question meatball menu](https://github.com/LimeSurvey/react-app/assets/129734454/ca8cf74c-3299-442d-97b4-aac2f10ba48a)

2023-05-23 12:28 UTC, d-Pixie requested changes

2023-05-23 12:28 UTC, d-Pixie commented on src/components/SideBar/SideBarRow.js
> +          {...(!dragIcon && providedValue)}
This is bad form. If `!dragIcon` is `false` you will end up with a destruct on `false`. I would suggest you change how you set the variable above: 
```js
const hasProvidedValue = Boolean(dragIcon && provided?.dragHandleProps)
const providedValue = hasProvidedValue ? { ...provided.dragHandleProps } : {}
```
so you can just do `{...providedValue}` here instead.

2023-05-24 03:27 UTC, ramishenouda48 commented on src/components/SideBar/SideBar.scss
> +    opacity: 1 !important;
Thank you! updated :)

2023-05-24 03:29 UTC, ramishenouda48 commented on src/components/SideBar/SideBarRow.js
> +          {...(!dragIcon && providedValue)}
that's a good tip about the `false` thing, thank you 😃
I have removed the `dragIcon`, it was part of the old code... we are not really using it anymore

2023-05-24 03:33 UTC, ramishenouda48 commented on src/components/SideBar/SideBarRow.js
> +            cursor: !dragIcon ? 'grab' : 'pointer',
we are not using the `dragIcon` anymore so I have removed it and set the style directly in the `scss` file.

2023-05-24 03:38 UTC, ramishenouda48 commented on src/components/SurveyStructure/RowQuestionsList.js
> +  const reorderQuestions = (questionsList, startIndex, endIndex) => {
name naming 👍  updated. to `moveQuestion`.

2023-05-24 09:04 UTC, merged