QE-24 ec 02 group area
LimeSurvey/react-app pull request #43
Opened 2023-05-23 09:22 UTC by ramishenouda48

1. Added an accordion icon to unfold/collapse
2. Added number of included questions 
3. Added Duplicate group in the meatball menu
4. Added Delete group in the meatball menu 

![group unfold and collapse](https://github.com/LimeSurvey/react-app/assets/129734454/0d123eea-a9f6-4d7b-b34c-3a2a31834686)

2023-05-23 13:07 UTC, d-Pixie requested changes

2023-05-23 13:07 UTC, d-Pixie commented on src/helpers/RandomNumber.js
> +export const RandomNumber = (min = 0, max = 1000000) => {
It would have been better to extract a `newId` helper that takes the current gid and returns a new one. That way you could have changed the algorithm without having to go around and update all the call sites.

2023-05-24 04:00 UTC, ramishenouda48 commented on src/components/Survey/AddQuestion/AddQuestion.js
> +      ? lastQuestionInQuestionGroup?.qid + RandomNumber()
I'm actually still thinking of the best way to generate a temporary ID, I agree with your point and I did think about it before that with maximum bad luck things could overflow or get a duplicated ID. 
I think UUID will be sufficient as a temporary ID until the backend sends the generated ID.

2023-05-24 04:08 UTC, ramishenouda48 commented on src/components/Survey/QuestionGroups/QuestionGroup.js
> +      focusedGroupOrQuestion?.gid === questionGroup.gid &&
`I would suggest you refactor this into several useEffect calls. Something like this maybe:`
Looks cleaner, applied.

`When can focusedGroupOrQuestion?.gid === questionGroup.gid be true, but focusedGroupOrQuestion?.qid is false?`
it can be false or undefined if a `QuestionGroup` is focused, since question groups don't have a `qid`, `questionId`.

2023-05-24 05:30 UTC, ramishenouda48 commented on src/components/Survey/QuestionGroups/QuestionGroups.js
> +    if (element && !element?.target?.classList?.contains('question-group')) {
makes a lot of sense, thank you 😃
I have done the following: 
1. removed the focusAndScrollToGroup function
2. added a questionGroupsRefs

```javascript
  const questionGroupsRefs = useRef([])
``` 
```javascript
  <div
          ref={(element) => (questionGroupsRefs.current[index] = element)}
``` 

4.Added  scrollToGroup function
```javascript
 const scrollToGroup = (questionGroupRef) => {
    const isQuestionGroupOnScreen = IsElementOnScreen(questionGroupRef)

    if (!isQuestionGroupOnScreen) {
      ScrollToElement(questionGroupRef, 100)
    }
  }
```

usage:
```javascript
      setFocusedQuestionGroup(duplicatedQuestionGroup)

      const questionGroupRef = questionGroupsRefs.current[index]
      scrollToGroup(questionGroupRef)
      ```

2023-05-24 05:38 UTC, ramishenouda48 commented on src/components/SurveyStructure/SurveyStructure.js
> +                    focusAndScrollToGroup(questionGroup, e)
Updated. I have removed that code, 
the purpose of the `e` element, was to ensure that the user clicked on the questionGroupTitle and not one of its children like the questions for instance
I have removed that and added `onTitleClick` which will fire when the user clicks on the group title.
```javascript
<RowQuestionGroup
  provided={provided}
  questionGroup={questionGroup}
  language={survey.language}
  update={(questionGroup) =>
    handleUpdateQuestionGroup(questionGroup, index)
  }
  duplicateGroup={() =>
    handleQuestionGroupDuplication(questionGroup, index)
  }
  deleteGroup={() => handleGroupDeletion(index)}
  onTitleClick={() => focusAndScrollToGroup(questionGroup)}
/>
```

2023-05-24 05:40 UTC, ramishenouda48 commented on src/components/Survey/QuestionGroups/QuestionGroups.js
> +  const focusAndScrollToGroup = (questionGroup, element) => {
makes a lot of sense, thank you 😃
I have done the following: 
1. removed the focusAndScrollToGroup function
2. added a questionGroupsRefs

```javascript
  const questionGroupsRefs = useRef([])
``` 
```javascript
  <div
          ref={(element) => (questionGroupsRefs.current[index] = element)}
``` 

4.Added  scrollToGroup function
```javascript
 const scrollToGroup = (questionGroupRef) => {
    const isQuestionGroupOnScreen = IsElementOnScreen(questionGroupRef)

    if (!isQuestionGroupOnScreen) {
      ScrollToElement(questionGroupRef, 100)
    }
  }
```

usage:
```javascript
      setFocusedQuestionGroup(duplicatedQuestionGroup)

      const questionGroupRef = questionGroupsRefs.current[index]
      scrollToGroup(questionGroupRef)
      ```

2023-05-24 06:13 UTC, ramishenouda48 commented on src/components/Survey/AddQuestion/AddQuestion.js
> +      ? lastQuestionInQuestionGroup?.qid + RandomNumber()
after discussion we decided to have questionGroupIndex, questionIndex added to the useFocusedQuestionOrGroupHook

2023-05-24 09:10 UTC, merged